### ISSUE TITLE
请问柯林斯本地词典从哪下载？是sqlite格式吗？

### ISSUE THREAD

**Issue by leitro** [louisun/iSearch#1]
请问柯林斯本地词典从哪下载？是sqlite格式吗？谢谢:-)

**Comment by louisun** [comment]
每个单词都是爬有道词典网页的，并没有柯林斯本地词典。只不过可以把单词及含义加到本地数据库里，有这个力气可以自己爬大量的单词存入。

**Comment by ghost** [comment]
什么时候支持语句呀
