### ISSUE TITLE
输入S没有反应

### ISSUE THREAD

**Issue by RogueAndMagic** [louisun/iSearch#6]
我输入pip install iSearch 提示我安装成功了，然后我输入s提示我S不是一个命令。

**Comment by louisun** [comment]
这个工具适合 Linux 或 Mac OS 的终端，Windows 暂不适合用

**Comment by RogueAndMagic** [comment]
我是kali哦

**Comment by louisun** [comment]
那可以用 alias 解决

**Comment by RogueAndMagic** [comment]
可以详细点嘛，本人对linux不是很了解的

**Comment by louisun** [comment]
直接使用 s 无效，可通过设定alias来使用 s 命令。
例如：　在 .zshrc 或 .bashrc中加入
alias s='python /home/ubuntu/.local/lib/python2.7/site-packages/iSearch/isearch.py'

把上面路径替换成你自己 python 版本的包路径，alias 叫起别名，相当于把 s 替换成整条命令

**Comment by RogueAndMagic** [comment]
已解决，感谢！
